package com.raachi.memory.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val RaachiBrandNavy = Color(0xFF021964)
val RaachiBrandOrange = Color(0xFFFD7B07)
val RaachiSuccess = Color(0xFF168653)
val RaachiSuccessContainer = Color(0xFFD9F4E6)

internal val RaachiNavyContainer = Color(0xFFE8ECFF)
internal val RaachiOnNavyContainer = Color(0xFF102267)
internal val RaachiOrangeContainer = Color(0xFFFFF0E1)
internal val RaachiOnOrange = Color(0xFF321600)
internal val RaachiOnOrangeContainer = Color(0xFF743500)
internal val RaachiTeal = Color(0xFF257D68)
internal val RaachiTealContainer = Color(0xFFD7F2E9)
internal val RaachiBackground = Color(0xFFFAFAFE)
internal val RaachiSurface = Color(0xFFFFFFFF)
internal val RaachiSurfaceVariant = Color(0xFFF2F3F8)
internal val RaachiOutline = Color(0xFF747786)
internal val RaachiOutlineVariant = Color(0xFFD9DCE7)
internal val RaachiInk = Color(0xFF191B2D)
internal val RaachiMutedInk = Color(0xFF666A7A)
internal val RaachiError = Color(0xFFBA1A1A)
internal val RaachiErrorContainer = Color(0xFFFFDAD6)

internal val RaachiNavyDark = Color(0xFFBAC4FF)
internal val RaachiNavyContainerDark = Color(0xFF283873)
internal val RaachiOnNavyContainerDark = Color(0xFFDDE2FF)
internal val RaachiOrangeDark = Color(0xFFFFB66C)
internal val RaachiOrangeContainerDark = Color(0xFF8F3F00)
internal val RaachiOnOrangeDark = Color(0xFF1A1D2E)
internal val RaachiOnOrangeContainerDark = Color(0xFFFFDCC0)
internal val RaachiTealDark = Color(0xFF91D5C0)
internal val RaachiTealContainerDark = Color(0xFF164F42)
internal val RaachiSuccessDark = Color(0xFF7CDAA5)
internal val RaachiSuccessContainerDark = Color(0xFF0C5532)
internal val RaachiBackgroundDark = Color(0xFF191D2E)
internal val RaachiSurfaceDark = Color(0xFF22273A)
internal val RaachiSurfaceVariantDark = Color(0xFF2C3248)
internal val RaachiOutlineDark = Color(0xFF9194A3)
internal val RaachiOutlineVariantDark = Color(0xFF4B5268)
internal val RaachiInkDark = Color(0xFFF2F3FA)
internal val RaachiMutedInkDark = Color(0xFFC4C6D2)
internal val RaachiErrorDark = Color(0xFFFFB4AB)
internal val RaachiErrorContainerDark = Color(0xFF93000A)
