package com.raachi.memory.core.navigation

internal const val WELCOME_ROUTE = "welcome"
internal const val ONBOARDING_PROFILE_ROUTE = "onboarding_profile"
internal const val HOME_ROUTE = "home"
internal const val PROFILE_ROUTE = "profile"
internal const val EDIT_PROFILE_ROUTE = "edit_profile"
internal const val REMINDERS_ROUTE = "reminders"
internal const val LEDGER_ROUTE = "ledger"
internal const val ACTIVITY_ROUTE = "activity"
internal const val SETTINGS_ROUTE = "settings"
internal const val ABOUT_ROUTE = "about"
internal const val ADD_REMINDER_ROUTE = "reminder_editor"
internal const val EDIT_REMINDER_ROUTE = "reminder_editor/{reminderId}"
internal const val ADD_LEDGER_ROUTE = "ledger_editor"
internal const val EDIT_LEDGER_ROUTE = "ledger_editor/{ledgerId}"
internal const val EXPENSES_ROUTE = "expenses"
internal const val ADD_EXPENSE_TRANSACTION_ROUTE = "expense_editor"
internal const val EDIT_EXPENSE_TRANSACTION_ROUTE = "expense_editor/{transactionId}"
